<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user.proto

namespace GPBMetadata;

class User
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a560a0a757365722e70726f746f22300a0455736572120c0a046e616d65180120012809120d0a05656d61696c180220012809120b0a03616765180320012805420ee2020b4750424d65746164617461620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

